
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tyler
 */
public class BetterButtonPanel extends javax.swing.JPanel {

    //public ClausePanel sel;         // This is the top selection box. The first selection goes in here.
    //public ClausePanel n;           // This is the bottom selection box. The second selection goes in here. 
    private int command;            // 
    private int numSuper;           // 
    private int x;                  // 
    private TestApplet myParent;    //
    private XMLTreeNode first;      // Holds the Node used in the first box
    private XMLTreeNode last;       // Holds the Node used in the last box
    
    /**
     * Toggle the enabled property for the buttons.
     * @param t the value to assign to the enabled attribute of the buttons
     */
    public final void toggleB(boolean t) {
        cmdEdit.setEnabled(t);
        cmdGroup.setEnabled(t);
        cmdRemove.setEnabled(t);
        cmdSplit.setEnabled(t);
        cmdTreeModel.setEnabled(t);
    }
    
    /**
     * Creates new form BetterButtonPanel
     */
    public BetterButtonPanel(int x, TestApplet mp) {
        initComponents();
        
        this.x = x;
        command = -1; // Why?
        Clause temp = null;
        //sel = new ClausePanel(temp); // Why?
        //n = new ClausePanel(temp); // Why?
        
        toggleB(false);

        myParent = mp;
    }

    /**
     * Sets the Combobox with the correct number of Nodes to be grouped.
     */
    public void setUpCombo() {
        XMLTreeNode parent = (XMLTreeNode) myParent.getNodePanel().getSelected().getParent();
        int currentI = parent.getIndex(myParent.getNodePanel().getSelected()) + 1;
        int totalC = parent.getChildCount();
        for (int i = 0; i < totalC - currentI; i++) {
            comSuperSize.addItem(new Integer(i + 1));
        }
    }
    
    public void setSelected(XMLTreeNode selected) {
        // Try to set the information based on the Node.
        try {
            toggleB(true);
            
            first = selected;
            txtFirstChapter.setText(selected.getChap());
            txtFirstVerse.setText(selected.getVrse());
            txtFirstConjunction.setText(selected.getConj());
            txtFirstText.setText(selected.getData());
        } catch (NullPointerException edit) { // Insert blanks if it fails.
            txtFirstChapter.setText("");
            txtFirstVerse.setText("");
            txtFirstConjunction.setText("");
            txtFirstText.setText("");
            
            txtLastChapter.setText("");
            txtLastVerse.setText("");
            txtLastConjunction.setText("");
            txtLastText.setText("");
        }
    }
    
    public void setOtherSelected(XMLTreeNode selected) {
        // Try to set the information based on the Node.
        try {
            toggleB(true); // Note that the buttons will not be turned on if this section fails.
            txtLastChapter.setText(selected.getChap());
            txtLastVerse.setText(selected.getVrse());
            txtLastConjunction.setText(selected.getConj());
            txtLastText.setText(selected.getData());
        } catch (NullPointerException edit) { // Insert blanks if it fails.
            txtFirstChapter.setText("");
            txtFirstVerse.setText("");
            txtFirstConjunction.setText("");
            txtFirstText.setText("");
        }
    }
    
    public int getSuperSizeSelectedIndex() {
        return comSuperSize.getSelectedIndex();
    }
    
    /*public static void main(String[] args) {
        try { // I want to add this code at some point. This will make it look much better, but we'll worry about making it pretty later.
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
        }

        javax.swing.JFrame myFrame = new javax.swing.JFrame("Testing");
        myFrame.setLayout(new java.awt.GridLayout(1, 1));
        myFrame.add(new BetterButtonPanel());
        myFrame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        myFrame.pack();
        myFrame.setVisible(true);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstChapter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFirstVerse = new javax.swing.JTextField();
        txtFirstConjunction = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFirstText = new javax.swing.JTextArea();
        txtLastChapter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLastVerse = new javax.swing.JTextField();
        txtLastConjunction = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLastText = new javax.swing.JTextArea();
        cmdOkay = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        cmdTreeModel = new javax.swing.JButton();
        cmdSplit = new javax.swing.JButton();
        cmdEdit = new javax.swing.JButton();
        cmdRemove = new javax.swing.JButton();
        cmdGroup = new javax.swing.JButton();
        comSuperSize = new javax.swing.JComboBox();

        txtFirstChapter.setColumns(2);
        txtFirstChapter.setNextFocusableComponent(txtFirstVerse);

        jLabel1.setText(":");

        txtFirstVerse.setColumns(2);
        txtFirstVerse.setNextFocusableComponent(txtFirstConjunction);

        txtFirstConjunction.setColumns(8);
        txtFirstConjunction.setNextFocusableComponent(txtFirstText);

        txtFirstText.setColumns(17);
        txtFirstText.setLineWrap(true);
        txtFirstText.setRows(5);
        jScrollPane1.setViewportView(txtFirstText);

        txtLastChapter.setColumns(2);
        txtLastChapter.setNextFocusableComponent(txtLastVerse);

        jLabel2.setText(":");

        txtLastVerse.setColumns(2);
        txtLastVerse.setNextFocusableComponent(txtLastConjunction);

        txtLastConjunction.setColumns(8);
        txtLastConjunction.setNextFocusableComponent(txtLastText);

        txtLastText.setColumns(17);
        txtLastText.setLineWrap(true);
        txtLastText.setRows(5);
        jScrollPane2.setViewportView(txtLastText);

        cmdOkay.setText("Okay");
        cmdOkay.setNextFocusableComponent(cmdCancel);

        cmdCancel.setText("Cancel");
        cmdCancel.setNextFocusableComponent(cmdTreeModel);

        cmdTreeModel.setText("Tree Model");
        cmdTreeModel.setNextFocusableComponent(cmdSplit);

        cmdSplit.setText("Split");
        cmdSplit.setNextFocusableComponent(cmdEdit);

        cmdEdit.setText("Edit");
        cmdEdit.setNextFocusableComponent(cmdRemove);

        cmdRemove.setText("Remove");
        cmdRemove.setNextFocusableComponent(cmdGroup);

        cmdGroup.setText("Group");
        cmdGroup.setNextFocusableComponent(comSuperSize);

        comSuperSize.setNextFocusableComponent(txtFirstChapter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFirstChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstVerse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFirstConjunction))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtLastChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastVerse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtLastConjunction))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmdGroup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdTreeModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdOkay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdSplit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comSuperSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstVerse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstConjunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastVerse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastConjunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdOkay)
                    .addComponent(cmdCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdTreeModel)
                    .addComponent(cmdSplit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdEdit)
                    .addComponent(cmdRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdGroup)
                    .addComponent(comSuperSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JButton cmdGroup;
    private javax.swing.JButton cmdOkay;
    private javax.swing.JButton cmdRemove;
    private javax.swing.JButton cmdSplit;
    private javax.swing.JButton cmdTreeModel;
    private javax.swing.JComboBox comSuperSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtFirstChapter;
    private javax.swing.JTextField txtFirstConjunction;
    private javax.swing.JTextArea txtFirstText;
    private javax.swing.JTextField txtFirstVerse;
    private javax.swing.JTextField txtLastChapter;
    private javax.swing.JTextField txtLastConjunction;
    private javax.swing.JTextArea txtLastText;
    private javax.swing.JTextField txtLastVerse;
    // End of variables declaration//GEN-END:variables
}
